#!/usr/bin/env bash
#transferss a file from our client to a server
args=("$@")
if [[ $# -lt 3 ]];then
	echo "Usage: 0-transfer_file PATH-TO-FILE IP USERNAME PATH_TO_SSH-KEY"
elif [[ $# -lt 4 ]];then
	scp -o StrictHostKeyChecking=no "$1" "$3@$1":~/
else
	scp  -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
