#!/usr/bin/env bash
#configures a new ubuntu machine with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6. \*
sed -i '/errorfile  504/a listen thekeimah' /etc/haproxy/haproxy.cfg
sed -i '/listen thekeimah/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 20505-web-01 18.232.38.189:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 20505-web-01 18.232.38.189:80 check/a         server 20505-web-02 34.204.198.100:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
